### ISSUE TITLE
Embedding Reports and sharing

### ISSUE THREAD

**Issue by philipplenz** [taarskog/crm-powerbi-viewer#10]
Hello,

I've successfully installed the tool and I can embed Reports for my login. If I use another login, I can't open the report. 
Are this solution working with the Power BI Embedded API via Azure?

Thanks a lot!

**Comment by taarskog** [comment]
You have to make the report available to a group (move it from your workspace to group workspaces). All members of the group can see the report.

Also in CRM you need to set the groupId:
type=report&reportId=\<reportId\>**&groupId=\<groupId\>**

**Comment by rstephanee** [comment]
We've gotten this to work, but it's inconsistent between users.  For some users, the report with filters show up every time.  For other users, only "Content Not Available" displays every time.  All the users are in the same group and can access them directly from PBI.  Behavior is same in IE & Chrome.  Any ideas on what security settings are preventing access by certain users?

**Comment by taarskog** [comment]
Just to make sure we are talking about the same thing: by group are you talking about a Group Workspace created in Power BI or a Security Group in Active Directory?

Please also verify that you have not limited the users access to the crm-power-bi-viewer application in your Azure Actice Directory Configuration.

**Comment by rstephanee** [comment]
Hi Trond,

Thanks for responding.  Group Workspace in PBI.  I will check on the Azure AD configuration—thanks for that tip.

Regards,
Robert

Robert Stephan, CTO
M: 407.808.2133

[email signature]<http://www.ecuityedge.com/>
www.ecuityedge.com<http://www.ecuityedge.com/>

**Comment by rstephanee** [comment]
Hi Trond,

We must have everything setup correctly at a macro level because 3 users (myself and two client engineers) can see and interact with the report perfectly, both inside their network and externally.  But everyone else cannot (they just get “Content Not Available” which must be an authentication issue).

Would you be willing and able to sub-contract with our company to get this working?  It is a high priority item for this enterprise client.

Let me know.

Thanks,
Robert

Robert Stephan, CTO
M: 407.808.2133

[email signature]<http://www.ecuityedge.com/>
www.ecuityedge.com<http://www.ecuityedge.com/>
