### ISSUE TITLE
Unable to See Custom Reports

### ISSUE THREAD

**Issue by cvitacek** [taarskog/crm-powerbi-viewer#14]
Hi This solution looks to be very promissing.

The documentation of step 1 here (http://crm-powerbi-viewer.heiigjen.com/pages/add-report-to-dashboard.html) shows reports from the Microsoft Dynamics CRM Sales Content Pack.  However in the use case I am working on there are using only custom reports (no content packs have been installed), is this scenario supported?  

After following the setup instructions here is what the Configuration tab looks like;
![attachment1](https://cloud.githubusercontent.com/assets/10532316/23385124/9d5203dc-fd13-11e6-95ef-66d5e0a7990e.png)

Here is what the embedded report looks like;
![attachment2](https://cloud.githubusercontent.com/assets/10532316/23385123/9d4d63ea-fd13-11e6-839c-f12c86056e2d.png)

 and the link from that configuration error;
![attachment3](https://cloud.githubusercontent.com/assets/10532316/23385125/9d59ca22-fd13-11e6-9273-ea8b2f5c3225.png)

Any help would be appreciated.

**Comment by taarskog** [comment]
Seems to be an issue with accessing Power BI. Can you verify that you have given power-bi-viewer access to Power BI? See steps 9-11 on the [Azure AD](http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html) part of the installation guide and **remember to click save** (not stated explicitly in the guide).

**Comment by taarskog** [comment]
No feedback - assuming issue was resolved with proper AAD config.

**Comment by JacobHonig** [comment]
I solved it! The reports was not showing because some of the permissions was not set in AAD. 

I used the new guide that created the permissions automaticaly. But not all of the permissions pictured in the olg guid was selected. Ex. "View all Reports (preview)" was not selected. 

![image](https://user-images.githubusercontent.com/44808035/48121225-a52be080-e274-11e8-9d70-a26931a3be26.png)

When i selected them, the report is showing in the solution

![image](https://user-images.githubusercontent.com/44808035/48121324-e9b77c00-e274-11e8-9471-f21d131cf4ff.png)
