### ISSUE TITLE
When adding the web resource in CRM, it does not list the available Dashboards/Reports...

### ISSUE THREAD

**Issue by piterabrian** [taarskog/crm-powerbi-viewer#8]
When adding the PowerBI viewer to CRM, it appears to connect to PowerBI, but it does not list any dashboards/reports/...
![capture](https://cloud.githubusercontent.com/assets/15251948/15482040/9c0afef6-20fb-11e6-87b6-69ef40afd884.JPG)

**Comment by taarskog** [comment]
Make sure you have followed **absolutely all** the steps outlined in the [installation guide](http://crm-powerbi-viewer.heiigjen.com/#installation). Both the [Azure AD setup](http://crm-powerbi-viewer.heiigjen.com/pages/azure-ad.html) and the [CRM installation](http://crm-powerbi-viewer.heiigjen.com/pages/install-solution.html).

I successfully installed the latest release in a fresh environment a few days ago.

**Comment by taarskog** [comment]
Assuming that you forgot to update the clientid in the config file. v0.3.1 introduced an actual config file and due to this does not report an error when this is forgotten. Fixed in v0.3.2 (by commit 16c4edc). 

You do not need to install the new version just update the client id in the config file as described in the installation guide.
